### ISSUE TITLE
connect fail

### ISSUE THREAD

**Issue by lunanting** [Eugeny/tabby#10682]
Version: 1.0.227
Platform: Windows x64 10.0.26100
Plugins: sync-config
Frontend: xterm-webgl

 SSH  Connecting to H618-demo-sd
 X  Cannot read properties of undefined (reading 'filter')

all connections  same

**Comment by yLost** [comment]
Same here

**Comment by FusionStreak** [comment]
I am getting the same error, after updating from 1.0.223 -> 1.0.227

System info:

```txt
Version: 1.0.227
Platform: Windows x64 10.0.26100
Plugins: quick-cmds, cloud-settings-sync
Frontend: xterm-webgl
```

From debug tools:

```txt
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:15690 [hostApp] CLI arguments received: Object
error_handler.ts:45 ERROR TypeError: Cannot read properties of undefined (reading 'clear')
    at Object.next (C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:40664:47)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at emit (debounce.ts:84:20)
    at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
    at Subscriber.next (Subscriber.ts:75:12)
    at AsyncAction.<anonymous> (timer.ts:173:20)
    at AsyncAction._execute (AsyncAction.ts:120:12)
    at AsyncAction.execute (AsyncAction.ts:95:24)
    at AsyncScheduler.flush (AsyncScheduler.ts:40:27)
    at timer (zone.js:2355:41)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at invokeTask (zone.js:483:34)
    at ZoneTask.invoke (zone.js:472:48)
    at data.args.<computed> (zone.js:2335:32)
    at sentryWrapped (helpers.ts:87:17)
handleError @ error_handler.ts:45
// ....
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:9284 SSH session initialization failed TypeError: Cannot read properties of undefined (reading 'filter')
    at SSHSession.<anonymous> (C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:8250:72)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:6809:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
// ....
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:15690 [ssh-10.1.1.75-22]  !  Agent auth selected, but no running Agent process is found
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:15690 [ssh-10.1.1.75-22]  !  Agent auth selected, but no running Agent process is found
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:15690 [ssh-10.1.1.75-22]  !  Agent auth selected, but no running Agent process is found
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:15690 [ssh-10.1.1.75-22]  !  Agent auth selected, but no running Agent process is found
C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:9284 SSH session initialization failed TypeError: Cannot read properties of undefined (reading 'filter')
    at SSHSession.<anonymous> (C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:8250:72)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:6809:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
```

Lines that causes error:

```js
// C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js
if (visibility) {
    // this.frontend.resizeHandler()
    const term = this.frontend.xterm;
    term._core._renderService.clear();
    term._core._renderService.handleResize(term.cols, term.rows);
}
```
```js
// C:\Users\<USER>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js
const algorithms = {};
for (const key of Object.values(SSHAlgorithmType)) {
    algorithms[key] = this.profile.options.algorithms[key].filter(x => supportedAlgorithms[key].includes(x));
}
```

**Comment by hzysoft** [comment]
after a few minutes, the ssh will session disconnect.
1.0.227
