### ISSUE TITLE
SFTP upload not working after update to 1.0.152

### ISSUE THREAD

**Issue by dbahmatov** [Eugeny/tabby#4383]
SFTP uploads not working after update to 1.0.152

**Comment by oushuifa** [comment]
me too

**Comment by dbahmatov** [comment]
there is some workaround?

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by amajauskas** [comment]
Hi Eugeny,

As an example - tried to upload "latest.log" - here are the console errors - thanks :)

from local dir: ~/Downloads/latest.log
to remote dir: ~/


`core.js:6456 ERROR TypeError: Cannot read property 'location' of null
    at ng-bootstrap.js:5636
    at Object.next (Subscriber.js:161)
    at SafeSubscriber.__webpack_modules__.85125.Subscriber._next (Subscriber.js:101)
    at SafeSubscriber.__webpack_modules__.85125.Subscriber.next (Subscriber.js:72)
    at zip.js:50
    at OperatorSubscriber._this._next (OperatorSubscriber.js:28)
    at OperatorSubscriber.__webpack_modules__.85125.Subscriber.next (Subscriber.js:72)
    at Subject.js:66
    at Object.errorContext (errorContext.js:22)
    at Subject.__webpack_modules__.63032.Subject.next (Subject.js:58)
    at ng-bootstrap.js:218
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28666)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at NgZone.run (core.js:28520)
    at ng-bootstrap.js:216
    at Object.next (Subscriber.js:161)
    at SafeSubscriber.__webpack_modules__.85125.Subscriber._next (Subscriber.js:101)
    at SafeSubscriber.__webpack_modules__.85125.Subscriber.next (Subscriber.js:72)
    at race.js:28
    at OperatorSubscriber._this._next (OperatorSubscriber.js:28)
    at OperatorSubscriber.__webpack_modules__.85125.Subscriber.next (Subscriber.js:72)
    at AsyncAction.<anonymous> (timer.js:28)
    at AsyncAction.__webpack_modules__.49702.AsyncAction._execute (AsyncAction.js:76)
    at AsyncAction.__webpack_modules__.49702.AsyncAction.execute (AsyncAction.js:64)
    at AsyncScheduler.__webpack_modules__.83643.AsyncScheduler.flush (AsyncScheduler.js:39)
    at timer (zone.js:2561)
    at ZoneDelegate.invokeTask (zone.js:406)
    at Zone.runTask (zone.js:178)
    at invokeTask (zone.js:487)
    at ZoneTask.invoke (zone.js:476)
    at data.args.<computed> (zone.js:2541)
    at sentryWrapped (helpers.js:72)
defaultErrorLogger @ core.js:6456
handleError @ core.js:6504
next @ core.js:29269
(anonymous) @ Subscriber.js:161
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ Subject.js:66
errorContext @ errorContext.js:22
__webpack_modules__.63032.Subject.next @ Subject.js:58
emit @ core.js:25946
(anonymous) @ core.js:28692
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28565
onHandleError @ core.js:28692
handleError @ zone.js:376
runTask @ zone.js:181
invokeTask @ zone.js:487
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2541
sentryWrapped @ helpers.js:72
setTimeout (async)
(anonymous) @ trycatch.js:86
scheduleTask @ zone.js:2543
scheduleTask @ zone.js:393
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:679
(anonymous) @ zone.js:2585
proto.<computed> @ zone.js:975
setTimeout @ timeoutProvider.js:32
reportUnhandledError @ reportUnhandledError.js:7
(anonymous) @ Subscriber.js:168
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ zip.js:50
OperatorSubscriber._this._next @ OperatorSubscriber.js:28
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ Subject.js:66
errorContext @ errorContext.js:22
__webpack_modules__.63032.Subject.next @ Subject.js:58
(anonymous) @ ng-bootstrap.js:218
invoke @ zone.js:372
onInvoke @ core.js:28666
invoke @ zone.js:371
run @ zone.js:134
run @ core.js:28520
(anonymous) @ ng-bootstrap.js:216
(anonymous) @ Subscriber.js:161
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ race.js:28
OperatorSubscriber._this._next @ OperatorSubscriber.js:28
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ timer.js:28
__webpack_modules__.49702.AsyncAction._execute @ AsyncAction.js:76
__webpack_modules__.49702.AsyncAction.execute @ AsyncAction.js:64
__webpack_modules__.83643.AsyncScheduler.flush @ AsyncScheduler.js:39
timer @ zone.js:2561
invokeTask @ zone.js:406
runTask @ zone.js:178
invokeTask @ zone.js:487
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2541
sentryWrapped @ helpers.js:72
setInterval (async)
(anonymous) @ trycatch.js:86
scheduleTask @ zone.js:2543
scheduleTask @ zone.js:393
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:679
(anonymous) @ zone.js:2585
proto.<computed> @ zone.js:975
setInterval @ intervalProvider.js:32
__webpack_modules__.49702.AsyncAction.requestAsyncId @ AsyncAction.js:49
__webpack_modules__.49702.AsyncAction.schedule @ AsyncAction.js:44
Scheduler.schedule @ Scheduler.js:13
(anonymous) @ timer.js:26
Observable._trySubscribe @ Observable.js:41
(anonymous) @ Observable.js:35
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
(anonymous) @ takeUntil.js:11
(anonymous) @ lift.js:14
(anonymous) @ Observable.js:30
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
_loop_1 @ race.js:21
(anonymous) @ race.js:32
Observable._trySubscribe @ Observable.js:41
(anonymous) @ Observable.js:35
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
(anonymous) @ takeUntil.js:11
(anonymous) @ lift.js:14
(anonymous) @ Observable.js:30
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
(anonymous) @ ng-bootstrap.js:214
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28565
ngbRunTransition @ ng-bootstrap.js:211
hide @ ng-bootstrap.js:5691
_removeModalElements @ ng-bootstrap.js:5632
close @ ng-bootstrap.js:5598
activeModal.close @ ng-bootstrap.js:5887
cancel @ /opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:36503
(anonymous) @ /opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:36496
(anonymous) @ Subscriber.js:161
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ Subject.js:66
errorContext @ errorContext.js:22
__webpack_modules__.63032.Subject.next @ Subject.js:58
ngOnDestroy @ /opt/Tabby/resources/builtin-plugins/tabby-core/dist/index.js:22808
callProviderLifecycles @ core.js:24997
callElementProvidersLifecycles @ core.js:24965
callLifecycleHooksChildrenFirst @ core.js:24955
destroyView @ core.js:32045
destroy @ core.js:24399
(anonymous) @ ng-bootstrap.js:5640
(anonymous) @ Subscriber.js:161
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ zip.js:50
OperatorSubscriber._this._next @ OperatorSubscriber.js:28
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ Subject.js:66
errorContext @ errorContext.js:22
__webpack_modules__.63032.Subject.next @ Subject.js:58
(anonymous) @ ng-bootstrap.js:218
invoke @ zone.js:372
onInvoke @ core.js:28666
invoke @ zone.js:371
run @ zone.js:134
run @ core.js:28520
(anonymous) @ ng-bootstrap.js:216
(anonymous) @ Subscriber.js:161
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ race.js:28
OperatorSubscriber._this._next @ OperatorSubscriber.js:28
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ timer.js:28
__webpack_modules__.49702.AsyncAction._execute @ AsyncAction.js:76
__webpack_modules__.49702.AsyncAction.execute @ AsyncAction.js:64
__webpack_modules__.83643.AsyncScheduler.flush @ AsyncScheduler.js:39
timer @ zone.js:2561
invokeTask @ zone.js:406
runTask @ zone.js:178
invokeTask @ zone.js:487
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2541
sentryWrapped @ helpers.js:72
setInterval (async)
(anonymous) @ trycatch.js:86
scheduleTask @ zone.js:2543
scheduleTask @ zone.js:393
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:679
(anonymous) @ zone.js:2585
proto.<computed> @ zone.js:975
setInterval @ intervalProvider.js:32
__webpack_modules__.49702.AsyncAction.requestAsyncId @ AsyncAction.js:49
__webpack_modules__.49702.AsyncAction.schedule @ AsyncAction.js:44
Scheduler.schedule @ Scheduler.js:13
(anonymous) @ timer.js:26
Observable._trySubscribe @ Observable.js:41
(anonymous) @ Observable.js:35
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
(anonymous) @ takeUntil.js:11
(anonymous) @ lift.js:14
(anonymous) @ Observable.js:30
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
_loop_1 @ race.js:21
(anonymous) @ race.js:32
Observable._trySubscribe @ Observable.js:41
(anonymous) @ Observable.js:35
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
(anonymous) @ takeUntil.js:11
(anonymous) @ lift.js:14
(anonymous) @ Observable.js:30
errorContext @ errorContext.js:22
Observable.subscribe @ Observable.js:26
(anonymous) @ ng-bootstrap.js:214
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28565
ngbRunTransition @ ng-bootstrap.js:211
hide @ ng-bootstrap.js:5691
_removeModalElements @ ng-bootstrap.js:5632
close @ ng-bootstrap.js:5598
activeModal.close @ ng-bootstrap.js:5887
(anonymous) @ /opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:36498
fulfilled @ /opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:34456
invoke @ zone.js:372
onInvoke @ core.js:28666
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1276
invokeTask @ zone.js:406
onInvokeTask @ core.js:28653
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:582
Promise.then (async)
scheduleMicroTask @ zone.js:565
scheduleTask @ zone.js:396
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1266
resolvePromise @ zone.js:1204
(anonymous) @ zone.js:1120
(anonymous) @ zone.js:1136
apply @ /opt/Tabby/resources/app.asar/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54
(anonymous) @ /opt/Tabby/resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js:345
(anonymous) @ /opt/Tabby/resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js:327
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
Show 180 more frames
/opt/Tabby/resources/builtin-plugins/tabby-core/dist/index.js:17171 [sftp] Uploading into /home/am/latest.log
core.js:6456 ERROR Error: Uncaught (in promise): Error: No such file
Error: No such file
    at 101 (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:10193)
    at SFTP.push (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:7993)
    at CHANNEL_DATA (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:3990)
    at 94 (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:14267)
    at Protocol.onPayload (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:7659)
    at GenericDecipherNative.decrypt (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:12967)
    at Protocol.parsePacket [as _parse] (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:7628)
    at Protocol.parse (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:5930)
    at Socket.<anonymous> (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:4177)
    at Socket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
    at Socket.Readable.push (internal/streams/readable.js:223)
    at TCP.onStreamRead (internal/stream_base_commons.js:188)
    at resolvePromise (zone.js:1213)
    at zone.js:1120
    at rejected (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:34457)
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28666)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at zone.js:1276
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28653)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
    at processTicksAndRejections (internal/process/task_queues.js:93)`

**Comment by dbahmatov** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Debug logs · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby)**A terminal for a more modern age (formerly Terminus) - Debug logs · Eugeny/tabby Wiki

Here is the log.

[-1629295255462.log](https://github.com/Eugeny/tabby/files/7007781/-1629295255462.log)

**Comment by markft** [comment]
I find that you have to select "SFTP", navigate to a directory that you have write access to, then upload. It seems like the default is trying to upload to /
